#define KEYWORDS\
X(alignas)                                                                     \
  X(alignof)                                                                   \
  X(_Atomic)                                                                   \
  X(auto)                                                                      \
  X(_BitInt)                                                                   \
  X(bool)                                                                      \
  X(break)                                                                     \
  X(case)                                                                      \
  X(char)                                                                      \
  X(_Complex)                                                                  \
  X(const)                                                                     \
  X(constexpr)                                                                 \
  X(continue)                                                                  \
  X(_Decimal128)                                                               \
  X(_Decimal32)                                                                \
  X(_Decimal64)                                                                \
  X(default)                                                                   \
  X(do)                                                                        \
  X(double)                                                                    \
  X(else)                                                                      \
  X(enum)                                                                      \
  X(extern)                                                                    \
  X(false)                                                                     \
  X(float)                                                                     \
  X(for)                                                                       \
  X(_Generic)                                                                  \
  X(goto)                                                                      \
  X(if)                                                                        \
  X(_Imaginary)                                                                \
  X(inline)                                                                    \
  X(int)                                                                       \
  X(long)                                                                      \
  X(_Noreturn)                                                                 \
  X(nullptr)                                                                   \
  X(register)                                                                  \
  X(restrict)                                                                  \
  X(return)                                                                    \
  X(short)                                                                     \
  X(signed)                                                                    \
  X(sizeof)                                                                    \
  X(static)                                                                    \
  X(static_assert)                                                             \
  X(struct)                                                                    \
  X(switch)                                                                    \
  X(thread_local)                                                              \
  X(true)                                                                      \
  X(typedef)                                                                   \
  X(typeof)                                                                    \
  X(typeof_unqual)                                                             \
  X(union)                                                                     \
  X(unsigned)                                                                  \
  X(void)                                                                      \
  X(volatile)                                                                  \
  X(while)

#define PUNCTUATOR                                                             \
  X("[")                                                                       \
  X("]")                                                                       \
  X("(")                                                                       \
  X(")")                                                                       \
  X("{")                                                                       \
  X("}")                                                                       \
  X(".")                                                                       \
  X("->")                                                                      \
  X("++")                                                                      \
  X("--")                                                                      \
  X("&")                                                                       \
  X("*")                                                                       \
  X("+")                                                                       \
  X("-")                                                                       \
  X("~")                                                                       \
  X("!")                                                                       \
  X("/")                                                                       \
  X("%")                                                                       \
  X("<<")                                                                      \
  X(">>")                                                                      \
  X("<")                                                                       \
  X(">")                                                                       \
  X("<=")                                                                      \
  X(">=")                                                                      \
  X("==")                                                                      \
  X("!=")                                                                      \
  X("^")                                                                       \
  X("|")                                                                       \
  X("&&")                                                                      \
  X("||")                                                                      \
  X("?")                                                                       \
  X(":")                                                                       \
  X("::")                                                                      \
  X(";")                                                                       \
  X("...")                                                                     \
  X("=")                                                                       \
  X("*=")                                                                      \
  X("/=")                                                                      \
  X("%=")                                                                      \
  X("+=")                                                                      \
  X("-=")                                                                      \
  X("<<=")                                                                     \
  X(">>=")                                                                     \
  X("&=")                                                                      \
  X("^=")                                                                      \
  X("|=")                                                                      \
  X(",")                                                                       \
  X("#")                                                                       \
  X("##")                                                                      \
  X("<:")                                                                      \
  X(":>")                                                                      \
  X("<%")                                                                      \
  X("%>")                                                                      \
  X("%:")                                                                      \
  X("%:%:")
